plugin-channels:
  - world_id
  - world_info
  - world_identifier
inform-player: false
encoding: UTF-8
mode: UUID
# valid: FILE (put world.id file in each world folder)
#        NAME (use world name - default)
#        UUID (use world UUID)
