name: ${name}
description: ${description}
author: Chris (Coaster3000 | Coaster4321)
authors: [ProgrammerDan, PatchyKnowly]
website: ${url}
version: ${version}
main: ${groupId}.${name}Plugin
commands:
 reloadWorldInfo:
  description: Execute the current debug code.
permissions:
 wuuid.reload:
  description: Controls access to configuration reloading.
  default: op
